spring.application.name=InsuranceSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/Insurance
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.springframework.web=DEBUG
app.jwt.secret=change-this-super-long-secret-key-at-least-64-characters-long-please-1234567890
app.jwt.ttl-ms=86400000

# ??????? ????? ??????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=insuranceSystem700@gmail.com
spring.mail.password=qtgg otip ccdg inqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.notifications.from=Insurance System <no-reply@insurancesystem.com>

# ???? ??? ????? ??????
spring.web.resources.static-locations=classpath:/static/,file:uploads/
