spring.application.name=InsuranceSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/InsuranceSystem
spring.datasource.username=postgres
spring.datasource.password=12121313
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.springframework.web=DEBUG

